# Site settings
title: hfoss-blog
email: bkantor01@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/hfoss-blog/" # the subpath of your site, e.g. /blog/
url: "http://benkantor.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  benkantor

# Build settings
markdown: kramdown
